L2 Onboarding UI Only
Synthetixio/synthetix-mintr pull request #323
Opened 2020-09-08 07:59 UTC by AndyTCF

2020-09-11 06:59 UTC, clementbalestrat requested changes
Nice job!

You kinda reinvented the wheel sometimes, so I'm sure you can remove plenty of code to be reusing existing components as indicated in my comments.

2020-09-11 06:59 UTC, clementbalestrat commented on src/components/L2Onboarding/StatBox.tsx
> +const Flex = styled.div`
There is already a file with basic styles, have a look at `styles/common.js`

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/Burn.tsx
> +import { useGetGasEstimate } from './hooks/useGetGasEstimate';
you probably don't need to export that do you? It's just gonna be used in this screen.

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/BurnIntermediary.tsx
> +	const calculateUSDSumOfSynths = useCallback(() => {
You don't need `useCallback` here. Just put it in`useEffect`

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/BurnIntermediary.tsx
> +			onClick: () => handleRedirectToTrade(),
Nice!

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/Deposit.tsx
> +	const gasEstimateError = useGetGasEstimate(
Not needed here. You will need to run estimate against the `transfer` function.

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/Deposit.tsx
> +	const getSNXBalance = useCallback(async () => {
`useCallback` not needed. Put everything in `useEffect`

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/L2Onboarding.tsx
> +	const fetchDepotData = useCallback(async () => {
Same. Put everything back into `useEffect`

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/hooks/useGetDebtData.tsx
> +export const useGetDebtData = (walletAddress: string, sUSDBytes: string) => {
I'm quite sure you can have all the debt data from Redux. Have a look at `DebtStatus`

2020-09-11 06:59 UTC, clementbalestrat commented on src/pages/L2Onboarding/hooks/useGetGasEstimate.tsx
> +import { useState, useEffect } from 'react';
As said earlier, you can probably get rid of that file.

2020-09-11 06:59 UTC, clementbalestrat commented on src/screens/MintrTabs/Home/Home.js
> +	useEffect(() => {
maybe call `setRedirectTrade(false)` directly from the `Trade` screen.

2020-09-11 06:59 UTC, clementbalestrat commented on src/screens/MintrTabs/LPRewards/LPRewards.js
> +// const DistributionRow = styled.div`
To delete if not needed

2020-09-11 06:59 UTC, clementbalestrat commented on src/styles/l2/l2colors.ts
> +interface IL2Colors {
Maybe rename that ILayer2Icon. Because then you've got plenty of `l1, l2, l3` which can be confusing.

2020-09-11 07:01 UTC, clementbalestrat commented on src/components/L2Onboarding/GasSettings.tsx
> +import React from 'react';
(I was talking about the file itself)

2020-09-11 09:26 UTC, AndyTCF commented on src/pages/L2Onboarding/Deposit.tsx
> +	const gasEstimateError = useGetGasEstimate(
Need clarification for this, but we can talk about it when the OVM address is ready :)

2020-09-13 07:38 UTC, clementbalestrat requested changes
Nice!  few minor comments.

I think you don't need to create `useGetDebtData` and fetch everything from Redux.

2020-09-13 07:38 UTC, clementbalestrat commented on src/pages/L2Onboarding/Success.tsx
> +const CTAButton = styled(ButtonPrimary)`
Maybe export that style into a `component` folder sitting in `/L2Onboarding` so you can reuse it everywhere.

2020-09-13 07:38 UTC, clementbalestrat commented on src/pages/L2Onboarding/BurnIntermediary.tsx
> +		const calculateUSDSumOfSynths = () => {
you can just do:

`if (!walletBalancesWithRates) return`

and then remove:

`if (walletBalancesWithRates)...`

2020-09-13 07:38 UTC, clementbalestrat commented on src/pages/L2Onboarding/Burn.tsx
> +				const results = await Promise.all([
I'm pretty sure you can fetch all the required data from Redux?
debt, synths balances etc..

2020-09-14 01:38 UTC, AndyTCF commented on src/pages/L2Onboarding/Burn.tsx
> +		burnAmount,
@clementbalestrat removed the maxBurn and maxBurnNB

2020-09-14 01:39 UTC, AndyTCF commented on src/pages/L2Onboarding/Burn.tsx
> +					const amountToBurn = snxJSConnector.utils.parseEther(burnAmount.toString());
Can I use burnAmount in this way? Straight from the debtData and converted to string

2020-10-04 19:20 UTC, jwineman commented on src/screens/MintrActions/Migrate/OneInchCard.tsx
> +		snxJSConnector.snxJS.contractSettings.signer
Is this the best way to get the signer?

2020-10-06 05:48 UTC, clementbalestrat commented on src/screens/MintrActions/Migrate/OneInchCard.tsx
> +		snxJSConnector.snxJS.contractSettings.signer
yep

2020-10-06 10:35 UTC, AndyTCF commented on src/screens/MintrActions/Migrate/OneInchCard.tsx
> +		snxJSConnector.snxJS.contractSettings.signer
const {
          signer
	} = snxJSConnector;

2020-10-06 10:35 UTC, AndyTCF commented on src/screens/MintrActions/Migrate/OneInchCard.tsx
> +		snxJSConnector.snxJS.contractSettings.signer
`	const {
		snxJS: { EtherCollateral, EtherCollateralsUSD },
		signer
	} = snxJSConnector;`

2020-10-06 10:38 UTC, AndyTCF commented on src/hooks/useOneInch.ts
> +					gasPrice,
@jwineman pretty sure gasPrice is also a BN in wei and also use the estimated gas limit from the estimate you did 

example in synthetix exchange 

```	const gasEstimate = await contract.estimate.liquidateLoan(loanOwner, loanIDStr, debtToCover);
			const updatedGasEstimate = normalizeGasLimit(Number(gasEstimate));
			setLocalGasLimit(updatedGasEstimate);

			const tx = await contract.liquidateLoan(loanOwner, loanIDStr, debtToCover, {
				gasPrice: gasInfo.gasPrice * GWEI_UNIT,
				gasLimit: updatedGasEstimate,
			});```

2020-10-12 10:40 UTC, merged