Hide Actions.
Synthetixio/synthetix-mintr pull request #361
Opened 2020-10-09 22:17 UTC by jwineman

Hide Mint/Burn/Claim etc if on goerli-test.

<img width="944" alt="Screen Shot 2020-10-09 at 3 09 31 PM" src="https://user-images.githubusercontent.com/6947158/95635870-7dd28500-0a42-11eb-8cfa-14b9042355d3.png">

2020-10-09 22:49 UTC, clementbalestrat requested changes

2020-10-09 22:49 UTC, clementbalestrat commented on src/components/Banner/L2Banner.tsx
> +
@jwineman can you remove that?

2020-10-09 22:49 UTC, clementbalestrat commented on src/screens/MintrTabs/Home/index.js
> +export { default } from './Home.tsx';
you probably don't need that

2020-10-09 22:49 UTC, clementbalestrat commented on src/screens/MintrPanel/MintrPanel.js
> +							disabled={
Logic is good but a bit dirty. Can you create an object like `RESTRICTED_TABS`

then you'll test if `RESTRICTED_TABS[networkID][tab]` exists in the `disabled` prop

2020-10-09 23:04 UTC, jwineman commented on src/screens/MintrTabs/Home/index.js
> +export { default } from './Home.tsx';
```
export { default } from './Home';
```
gives me
```
Failed to compile
./src/screens/MintrTabs/Home/Home.js
Error: ENOENT: no such file or directory, open '/Users/johnwineman/synthetix/synthetix-mintr/src/screens/MintrTabs/Home/Home.js'
```

2020-10-11 22:56 UTC, clementbalestrat approved these changes

2020-10-11 22:57 UTC, merged