Feature/mintr refetches
Synthetixio/synthetix-mintr pull request #364
Opened 2020-10-12 03:18 UTC by AndyTCF

2020-10-13 05:26 UTC, clementbalestrat requested changes
@andytcf this is great man. Well done. A few minor stuff to update and then I'll merge it :)

2020-10-13 05:26 UTC, clementbalestrat commented on src/helpers/notifyHelper.js
> +		}, 15000);
Have you tried with a lower timeout? like 5 or 10 secs?

`txConfirmed` is when the transaction is mined so we shouldn't need to wait 15 secs to get the updated data.

2020-10-13 05:27 UTC, clementbalestrat commented
@andytcf also if you could fix the merge conflict

2020-10-14 01:28 UTC, andytcf commented on src/helpers/notifyHelper.js
> +		}, 15000);
tried the lower timeouts but 15 sec seems to be optimum for the event to be picked up, not entirely sure why so would welcome alternatives here

2020-10-14 02:31 UTC, clementbalestrat commented on src/helpers/notifyHelper.js
> +		}, 15000);
Yeah I guess it's because of Infura

2020-10-14 04:48 UTC, merged